name: Build ARM64 Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-arm64:
    runs-on: ubuntu-latest
    name: Build with Nuitka for ARM64

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

#    - name: Set up QEMU
#      uses: docker/setup-qemu-action@v2
#      with:
#        platforms: arm64

    - name: Run ARM64 build
      uses: pguyot/arm-runner-action@v2
      with:
        base_image: dietpi:rpi_armv8_bookworm
        commands: |
          apt-get update
          apt-get install -y python3 python3-pip python3-venv libgl1
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka
          nuitka --standalone --onefile --enable-plugin=numpy --output-dir=dist concierge.py
          cp dist/concierge.bin concierge-$(date +"%Y%m%d-%H%M")-$(git rev-parse --short HEAD)-aarch64

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: concierge-aarch64
        path: concierge-*-aarch64
